PlayerEvent Source Code Cleanup, add /kspam lawinfo
EntryPointKR/K-SPAM pull request #16
Opened 2017-01-19 02:45 UTC by ldmsys

PlayerEvent의 JoinMessage를 출력하는 소스 코드를 JoinMessageProcessor로 빼내서 간결하게 만들고,
/kspam lawinfo 명령어도 만들었습니다.

2017-01-19 05:53 UTC, EntryPointKR commented
라이선스에 대한 내용은 주석이며 실제로 내용을 출력하는 건 플러그인의 정보입니다
플러그인에 기여해주시려는 건 정말 감사합니다. 하지만 이 커밋이 자주 쓰이는 좋은 기능을 추가하기 보다 되려 구조가 더 복잡해지는게 아닐지 걱정돼요. 여기에 어떻게 생각하시나요?

2017-01-19 06:43 UTC, ldmsys commented
@EntryPointKR 제가 의도한것은 3마리 토끼를 잡자는것입니다.
1번째는 조인메시지가 나오게 하는것은 비동기로 진행시켜서 비록 0.몇초지만 그 시간을 확보하려는것입니다.
2번째는 아까 말했듯이 소스를 간결하게 하는것입니다.
3번째는 서버 들어오자마자 채팅청소가 자동으로 되는 서버가 있으니 플러그인 정보는 이런식으로 따로 확인가능하게 하는것입니다.

2017-01-19 06:57 UTC, EntryPointKR commented
@ldmsys 
메세지를 출력하는데 드는 시간은 아주 미세해 밀리세컨드로도 표현이 불가하므로 비동기로 실행하지 않아도 됩니다. 또 서버 관리자 쪽이

2017-01-19 07:30 UTC, EntryPointKR commented
메세지를 출력하는데 드는 시간은 아주 미세해 밀리세컨드로도 표현이 불가하므로 비동기로 실행하지 않아도 됩니다. 또 프로세서는 Processor 를 구현해야 하며 메세지의 경우 프로세서로 따로 빼는 것보다 Lang 열거형에 추가하는게 좋습니다.

그리고 lawinfo 라는 서브 명령어를 추가하는 방법보다 info 명령어에 출력되는 메세지를 추가하는 쪽이 나을 것 같아요

2017-01-19 09:10 UTC, ldmsys commented
Lang 열거형이 뭔가요?

2017-01-19 09:11 UTC, ldmsys commented
Lang 열거형이 뭔가요? 혹시 Lang.java 말씀하신건가요?

2017-01-19 09:14 UTC, EntryPointKR commented
@ldmsys Lang.java 가 열거형 클래스입니다

2017-01-19 10:03 UTC, ldmsys commented
해당사항 수정하였습니다. 수정된 코드 확인바랍니다.

2017-01-19 10:50 UTC, entrypointkr requested changes

2017-01-19 10:50 UTC, EntryPointKR commented on src/main/java/cloud/swiftnode/kspam/command/Commands.java
> +                                        /*
과도한 들여쓰기

2017-01-19 10:50 UTC, EntryPointKR commented on src/main/java/cloud/swiftnode/kspam/listener/PlayerListener.java
> +
필요 없는 공백

2017-01-19 10:50 UTC, EntryPointKR commented on src/main/java/cloud/swiftnode/kspam/listener/PlayerListener.java
> +                    밑 메세지 전송 코드를 제거 시 법적 책임을 물을 수 있습니다.
위 주석을 제거한 의도가 어떻게되나요?

2017-01-19 10:50 UTC, EntryPointKR commented on src/main/java/cloud/swiftnode/kspam/listener/PlayerListener.java
> +import cloud.swiftnode.kspam.abstraction.processor.ShutdownProcessor;
사용하지 않는 import

2017-01-20 03:49 UTC, ldmsys commented on src/main/java/cloud/swiftnode/kspam/listener/PlayerListener.java
> +                    밑 메세지 전송 코드를 제거 시 법적 책임을 물을 수 있습니다.
본 프로젝트에 기여했을 경우 밑 메시지에 ~~ 이 부분을 제거한 이유는
여기서 수정이 불가능하고 해당 부분에서 수정이 필요하기 때문입니다.

2017-01-20 03:50 UTC, ldmsys commented on src/main/java/cloud/swiftnode/kspam/listener/PlayerListener.java
> +
편집하다가 실수로 넣었나봅니다. 삭제하겠습니다.

2017-01-20 03:50 UTC, ldmsys commented on src/main/java/cloud/swiftnode/kspam/listener/PlayerListener.java
> +import cloud.swiftnode.kspam.abstraction.processor.ShutdownProcessor;
제거하겠습니다.

2017-01-20 03:50 UTC, ldmsys commented on src/main/java/cloud/swiftnode/kspam/command/Commands.java
> +                                        /*
제 편집기와 실제랑 차이가 많이 나네요;; 수정하겠습니다.

2017-01-20 04:35 UTC, entrypointkr requested changes

2017-01-20 04:35 UTC, EntryPointKR commented on src/main/java/cloud/swiftnode/kspam/listener/PlayerListener.java
> +                    밑 메세지 전송 코드를 제거 시 법적 책임을 물을 수 있습니다.
과도한 들여쓰기

2017-01-20 04:36 UTC, entrypointkr requested changes

2017-01-20 04:36 UTC, EntryPointKR commented on src/main/java/cloud/swiftnode/kspam/util/Lang.java
> +    "&c[ K-SPAM ] &fhttps://github.com/EntryPointKR/K-SPAM\n"),
47, 48 라인을 한번씩 들여써주세요

2017-01-20 14:59 UTC, merged